// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Analytics records which tracking scripts a page carries.
 */
export class Analytics {
    "googleAnalytics": boolean;
    "gtag": boolean;
    "ga4Id"?: string;
    "gtmId"?: string;
    "facebookPixel": boolean;
    "hotjar": boolean;
    "mixpanel": boolean;

    /** Creates a new Analytics instance. */
    constructor($$source: Partial<Analytics> = {}) {
        if (!("googleAnalytics" in $$source)) {
            this["googleAnalytics"] = false;
        }
        if (!("gtag" in $$source)) {
            this["gtag"] = false;
        }
        if (!("facebookPixel" in $$source)) {
            this["facebookPixel"] = false;
        }
        if (!("hotjar" in $$source)) {
            this["hotjar"] = false;
        }
        if (!("mixpanel" in $$source)) {
            this["mixpanel"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Analytics instance from a string or object.
     */
    static createFrom($$source: any = {}): Analytics {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Analytics($$parsedSource as Partial<Analytics>);
    }
}

export class GraphData {
    "nodes": GraphNode[];
    "edges": GraphEdge[];

    /**
     * Total is the run's full page count, so the UI can say
     * "showing top N of M by inlinks" instead of silently truncating.
     */
    "total": number;

    /** Creates a new GraphData instance. */
    constructor($$source: Partial<GraphData> = {}) {
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphData instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphData {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField1_0($$parsedSource["edges"]);
        }
        return new GraphData($$parsedSource as Partial<GraphData>);
    }
}

/**
 * GraphEdge is one deduplicated link between two included nodes.
 */
export class GraphEdge {
    "src": number;
    "dst": number;

    /** Creates a new GraphEdge instance. */
    constructor($$source: Partial<GraphEdge> = {}) {
        if (!("src" in $$source)) {
            this["src"] = 0;
        }
        if (!("dst" in $$source)) {
            this["dst"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphEdge instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphEdge {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphEdge($$parsedSource as Partial<GraphEdge>);
    }
}

/**
 * GraphNode is one page in the picture.
 */
export class GraphNode {
    "id": number;
    "url": string;
    "status": number;
    "inlinks": number;
    "depth": number;
    "kind": string;
    "internal": boolean;

    /** Creates a new GraphNode instance. */
    constructor($$source: Partial<GraphNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("inlinks" in $$source)) {
            this["inlinks"] = 0;
        }
        if (!("depth" in $$source)) {
            this["depth"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("internal" in $$source)) {
            this["internal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphNode instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphNode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphNode($$parsedSource as Partial<GraphNode>);
    }
}

/**
 * Hop is one step of a redirect chain. LibreCrawl declares this field and never
 * fills it; populating it is one of the gaps this port closes.
 */
export class Hop {
    "url": string;
    "status": number;
    "location": string;

    /** Creates a new Hop instance. */
    constructor($$source: Partial<Hop> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("location" in $$source)) {
            this["location"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hop instance from a string or object.
     */
    static createFrom($$source: any = {}): Hop {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Hop($$parsedSource as Partial<Hop>);
    }
}

/**
 * Hreflang is one rel=alternate declaration.
 */
export class Hreflang {
    "lang": string;
    "url": string;

    /** Creates a new Hreflang instance. */
    constructor($$source: Partial<Hreflang> = {}) {
        if (!("lang" in $$source)) {
            this["lang"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hreflang instance from a string or object.
     */
    static createFrom($$source: any = {}): Hreflang {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Hreflang($$parsedSource as Partial<Hreflang>);
    }
}

/**
 * Image is one <img> found on a page.
 */
export class Image {
    "src": string;
    "alt": string;
    "width": string;
    "height": string;

    /**
     * filled only when image checking is on
     */
    "status"?: number;

    /** Creates a new Image instance. */
    constructor($$source: Partial<Image> = {}) {
        if (!("src" in $$source)) {
            this["src"] = "";
        }
        if (!("alt" in $$source)) {
            this["alt"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = "";
        }
        if (!("height" in $$source)) {
            this["height"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Image instance from a string or object.
     */
    static createFrom($$source: any = {}): Image {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Image($$parsedSource as Partial<Image>);
    }
}

/**
 * IssueInfo describes one rule to the frontend, so the Issues tab and the
 * Overview tree can label and colour it without hardcoding anything.
 */
export class IssueInfo {
    "code": string;
    "category": string;
    "severity": number;

    /** Creates a new IssueInfo instance. */
    constructor($$source: Partial<IssueInfo> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IssueInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): IssueInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IssueInfo($$parsedSource as Partial<IssueInfo>);
    }
}

/**
 * LinkRow is one edge as the detail pane shows it.
 */
export class LinkRow {
    "source": string;
    "target": string;
    "anchor": string;
    "placement": number;
    "flags": number;
    "targetStatus": number;

    /** Creates a new LinkRow instance. */
    constructor($$source: Partial<LinkRow> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("anchor" in $$source)) {
            this["anchor"] = "";
        }
        if (!("placement" in $$source)) {
            this["placement"] = 0;
        }
        if (!("flags" in $$source)) {
            this["flags"] = 0;
        }
        if (!("targetStatus" in $$source)) {
            this["targetStatus"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinkRow instance from a string or object.
     */
    static createFrom($$source: any = {}): LinkRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LinkRow($$parsedSource as Partial<LinkRow>);
    }
}

/**
 * Opportunity is one audit rolled up across the whole run.
 */
export class Opportunity {
    "auditId": string;
    "title": string;

    /**
     * Pages is how many URLs this audit fires on. Zero at the per-URL level,
     * filled only by the aggregate query.
     */
    "pages": number;
    "savingsMs": number;
    "savingsBytes": number;

    /** Creates a new Opportunity instance. */
    constructor($$source: Partial<Opportunity> = {}) {
        if (!("auditId" in $$source)) {
            this["auditId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("pages" in $$source)) {
            this["pages"] = 0;
        }
        if (!("savingsMs" in $$source)) {
            this["savingsMs"] = 0;
        }
        if (!("savingsBytes" in $$source)) {
            this["savingsBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Opportunity instance from a string or object.
     */
    static createFrom($$source: any = {}): Opportunity {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Opportunity($$parsedSource as Partial<Opportunity>);
    }
}

/**
 * OpportunityPage is one URL behind an audit.
 */
export class OpportunityPage {
    "url": string;
    "savingsMs": number;
    "savingsBytes": number;

    /** Creates a new OpportunityPage instance. */
    constructor($$source: Partial<OpportunityPage> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("savingsMs" in $$source)) {
            this["savingsMs"] = 0;
        }
        if (!("savingsBytes" in $$source)) {
            this["savingsBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpportunityPage instance from a string or object.
     */
    static createFrom($$source: any = {}): OpportunityPage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpportunityPage($$parsedSource as Partial<OpportunityPage>);
    }
}

/**
 * Options is the crawl configuration. It mirrors LibreCrawl's settings schema
 * plus the gaps this tool fills.
 * 
 * Following the house rule from indexcheck: the zero value means "default" for
 * numbers and enums, which normalized() fills in and clamps — but bools are
 * left alone, because a Go bool's zero value is false and there is no way to
 * tell "off" from "unset". Anything that is on by default (RespectRobots,
 * DiscoverSitemaps, FollowRedirects) has its default in the frontend's
 * DEFAULT_OPTIONS, and the frontend mirrors every clamp below.
 */
export class Options {
    /**
     * --- crawler ---
     * spider | list
     */
    "mode": string;

    /**
     * 0 = default 3
     */
    "maxDepth": number;

    /**
     * 0 = default 50000
     */
    "maxURLs": number;

    /**
     * per host, 0 = no artificial delay
     */
    "crawlDelayMs": number;
    "followRedirects": boolean;

    /**
     * fetch external URLs (never follow their links)
     */
    "crawlExternal": boolean;

    /**
     * treat sub.example.com as internal
     */
    "crawlSubdomains": boolean;

    /**
     * collapse ?a=1 into the bare path
     */
    "ignoreQueryParam": boolean;

    /**
     * Fetch the resources pages reference, like Screaming Frog's Crawl
     * Images/CSS/JavaScript. Without these the Images/CSS/JS tabs can only ever
     * show resources someone linked with an <a href> — in practice, nothing.
     */
    "crawlImages": boolean;
    "crawlCSS": boolean;
    "crawlJS": boolean;

    /**
     * --- requests ---
     * preset id
     */
    "userAgent": string;

    /**
     * 0 = default 10
     */
    "timeoutSec": number;

    /**
     * 0 = default 1
     */
    "retries": number;
    "acceptLanguage": string;

    /**
     * 0 = default 5
     */
    "concurrency": number;
    "respectRobots": boolean;

    /**
     * RespectCrawlDelay honours a robots.txt Crawl-delay. Off by default, which
     * is what Screaming Frog does: the directive spaces every request, so a
     * "Crawl-delay: 1" measured 1.1 URL/s where the same crawl otherwise ran at
     * 65 URL/s — and no thread count could recover it.
     */
    "respectCrawlDelay": boolean;
    "discoverSitemaps": boolean;
    "ignoreSSL": boolean;
    "customHeaders": { [_ in string]?: string };

    /**
     * UseProxy routes crawl requests through the proxy saved in Connections. Off
     * by default, like Screaming Frog: the crawl goes direct until the user ticks
     * it on here. A proxy that applies to every crawl merely because it sits in
     * the vault is a surprise — and a bottleneck, since all threads then share
     * one connection.
     */
    "useProxy": boolean;

    /**
     * --- filters ---
     */
    "includeExtensions": string[];
    "excludeExtensions": string[];

    /**
     * regex against the full URL
     */
    "includePatterns": string[];
    "excludePatterns": string[];

    /**
     * 0 = default 50
     */
    "maxFileSizeMB": number;

    /**
     * --- issues ---
     * path globs; nil = built-in defaults
     */
    "issueExclusions": string[];

    /**
     * prepend the built-in list
     */
    "useDefaultExcl": boolean;

    /**
     * --- duplicates ---
     */
    "enableDuplication": boolean;

    /**
     * 0 = default 0.85
     */
    "duplicationThreshold": number;

    /**
     * --- javascript rendering (phase 3) ---
     */
    "enableJavaScript": boolean;

    /**
     * only render URLs matching these; empty = all
     */
    "jsPatterns": string[];

    /**
     * hard cap enforced in Go, 0 = default 500
     */
    "jsMaxPages": number;

    /**
     * 0 = default 3000
     */
    "jsWaitMs": number;

    /**
     * 0 = default 30
     */
    "jsTimeoutSec": number;
    "jsViewportWidth": number;
    "jsViewportHeight": number;

    /**
     * 0 = default 3
     */
    "jsConcurrency": number;

    /**
     * --- pagespeed ---
     * On, every internal HTML page that answered 2xx is measured through the
     * PageSpeed Insights API while the crawl runs, the way Screaming Frog does
     * it. Deliberately uncapped: the user's ruling was parity, and the cost is
     * stated in the Configuration dialog instead of being clipped in silence.
     */
    "enablePageSpeed": boolean;

    /**
     * mobile | desktop
     */
    "psiStrategy": string;

    /** Creates a new Options instance. */
    constructor($$source: Partial<Options> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("maxDepth" in $$source)) {
            this["maxDepth"] = 0;
        }
        if (!("maxURLs" in $$source)) {
            this["maxURLs"] = 0;
        }
        if (!("crawlDelayMs" in $$source)) {
            this["crawlDelayMs"] = 0;
        }
        if (!("followRedirects" in $$source)) {
            this["followRedirects"] = false;
        }
        if (!("crawlExternal" in $$source)) {
            this["crawlExternal"] = false;
        }
        if (!("crawlSubdomains" in $$source)) {
            this["crawlSubdomains"] = false;
        }
        if (!("ignoreQueryParam" in $$source)) {
            this["ignoreQueryParam"] = false;
        }
        if (!("crawlImages" in $$source)) {
            this["crawlImages"] = false;
        }
        if (!("crawlCSS" in $$source)) {
            this["crawlCSS"] = false;
        }
        if (!("crawlJS" in $$source)) {
            this["crawlJS"] = false;
        }
        if (!("userAgent" in $$source)) {
            this["userAgent"] = "";
        }
        if (!("timeoutSec" in $$source)) {
            this["timeoutSec"] = 0;
        }
        if (!("retries" in $$source)) {
            this["retries"] = 0;
        }
        if (!("acceptLanguage" in $$source)) {
            this["acceptLanguage"] = "";
        }
        if (!("concurrency" in $$source)) {
            this["concurrency"] = 0;
        }
        if (!("respectRobots" in $$source)) {
            this["respectRobots"] = false;
        }
        if (!("respectCrawlDelay" in $$source)) {
            this["respectCrawlDelay"] = false;
        }
        if (!("discoverSitemaps" in $$source)) {
            this["discoverSitemaps"] = false;
        }
        if (!("ignoreSSL" in $$source)) {
            this["ignoreSSL"] = false;
        }
        if (!("customHeaders" in $$source)) {
            this["customHeaders"] = {};
        }
        if (!("useProxy" in $$source)) {
            this["useProxy"] = false;
        }
        if (!("includeExtensions" in $$source)) {
            this["includeExtensions"] = [];
        }
        if (!("excludeExtensions" in $$source)) {
            this["excludeExtensions"] = [];
        }
        if (!("includePatterns" in $$source)) {
            this["includePatterns"] = [];
        }
        if (!("excludePatterns" in $$source)) {
            this["excludePatterns"] = [];
        }
        if (!("maxFileSizeMB" in $$source)) {
            this["maxFileSizeMB"] = 0;
        }
        if (!("issueExclusions" in $$source)) {
            this["issueExclusions"] = [];
        }
        if (!("useDefaultExcl" in $$source)) {
            this["useDefaultExcl"] = false;
        }
        if (!("enableDuplication" in $$source)) {
            this["enableDuplication"] = false;
        }
        if (!("duplicationThreshold" in $$source)) {
            this["duplicationThreshold"] = 0;
        }
        if (!("enableJavaScript" in $$source)) {
            this["enableJavaScript"] = false;
        }
        if (!("jsPatterns" in $$source)) {
            this["jsPatterns"] = [];
        }
        if (!("jsMaxPages" in $$source)) {
            this["jsMaxPages"] = 0;
        }
        if (!("jsWaitMs" in $$source)) {
            this["jsWaitMs"] = 0;
        }
        if (!("jsTimeoutSec" in $$source)) {
            this["jsTimeoutSec"] = 0;
        }
        if (!("jsViewportWidth" in $$source)) {
            this["jsViewportWidth"] = 0;
        }
        if (!("jsViewportHeight" in $$source)) {
            this["jsViewportHeight"] = 0;
        }
        if (!("jsConcurrency" in $$source)) {
            this["jsConcurrency"] = 0;
        }
        if (!("enablePageSpeed" in $$source)) {
            this["enablePageSpeed"] = false;
        }
        if (!("psiStrategy" in $$source)) {
            this["psiStrategy"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Options instance from a string or object.
     */
    static createFrom($$source: any = {}): Options {
        const $$createField20_0 = $$createType4;
        const $$createField22_0 = $$createType5;
        const $$createField23_0 = $$createType5;
        const $$createField24_0 = $$createType5;
        const $$createField25_0 = $$createType5;
        const $$createField27_0 = $$createType5;
        const $$createField32_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("customHeaders" in $$parsedSource) {
            $$parsedSource["customHeaders"] = $$createField20_0($$parsedSource["customHeaders"]);
        }
        if ("includeExtensions" in $$parsedSource) {
            $$parsedSource["includeExtensions"] = $$createField22_0($$parsedSource["includeExtensions"]);
        }
        if ("excludeExtensions" in $$parsedSource) {
            $$parsedSource["excludeExtensions"] = $$createField23_0($$parsedSource["excludeExtensions"]);
        }
        if ("includePatterns" in $$parsedSource) {
            $$parsedSource["includePatterns"] = $$createField24_0($$parsedSource["includePatterns"]);
        }
        if ("excludePatterns" in $$parsedSource) {
            $$parsedSource["excludePatterns"] = $$createField25_0($$parsedSource["excludePatterns"]);
        }
        if ("issueExclusions" in $$parsedSource) {
            $$parsedSource["issueExclusions"] = $$createField27_0($$parsedSource["issueExclusions"]);
        }
        if ("jsPatterns" in $$parsedSource) {
            $$parsedSource["jsPatterns"] = $$createField32_0($$parsedSource["jsPatterns"]);
        }
        return new Options($$parsedSource as Partial<Options>);
    }
}

/**
 * PSIResult is one URL's PageSpeed verdict, as stored and as listed.
 * 
 * Two kinds of number live here and must not be confused. The Lighthouse ones
 * (Score, FCPMs…) are a simulated load Google runs on demand. The Crux ones are
 * what real Chrome users measured over the last 28 days — that is the data
 * Google ranks on, and it is absent for pages without enough traffic.
 * 
 * -1 means "not measured" throughout, which is not 0: a page nobody visits and
 * a page that genuinely scored 0 have to stay distinguishable.
 */
export class PSIResult {
    "url": string;
    "strategy": string;
    "fetchedAt": string;

    /**
     * lab (Lighthouse)
     * performance, 0-100
     */
    "score": number;
    "a11yScore": number;
    "seoScore": number;
    "bpScore": number;
    "fcpMs": number;
    "lcpMs": number;
    "cls": number;
    "tbtMs": number;
    "siMs": number;

    /**
     * field (Chrome User Experience Report, 28 days)
     * 
     * CruxSource says whose numbers these are: "url" for this page, "origin"
     * when the page itself lacked data and the whole domain's were used
     * instead. Showing borrowed numbers as if they were the page's own is the
     * one thing this must never do.
     * url | origin | ""
     */
    "cruxSource": string;

    /**
     * FAST | AVERAGE | SLOW | ""
     */
    "cruxVerdict": string;
    "cruxLcpMs": number;
    "cruxInpMs": number;
    "cruxCls": number;
    "cruxFcpMs": number;
    "cruxTtfbMs": number;
    "error"?: string;

    /** Creates a new PSIResult instance. */
    constructor($$source: Partial<PSIResult> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("strategy" in $$source)) {
            this["strategy"] = "";
        }
        if (!("fetchedAt" in $$source)) {
            this["fetchedAt"] = "";
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }
        if (!("a11yScore" in $$source)) {
            this["a11yScore"] = 0;
        }
        if (!("seoScore" in $$source)) {
            this["seoScore"] = 0;
        }
        if (!("bpScore" in $$source)) {
            this["bpScore"] = 0;
        }
        if (!("fcpMs" in $$source)) {
            this["fcpMs"] = 0;
        }
        if (!("lcpMs" in $$source)) {
            this["lcpMs"] = 0;
        }
        if (!("cls" in $$source)) {
            this["cls"] = 0;
        }
        if (!("tbtMs" in $$source)) {
            this["tbtMs"] = 0;
        }
        if (!("siMs" in $$source)) {
            this["siMs"] = 0;
        }
        if (!("cruxSource" in $$source)) {
            this["cruxSource"] = "";
        }
        if (!("cruxVerdict" in $$source)) {
            this["cruxVerdict"] = "";
        }
        if (!("cruxLcpMs" in $$source)) {
            this["cruxLcpMs"] = 0;
        }
        if (!("cruxInpMs" in $$source)) {
            this["cruxInpMs"] = 0;
        }
        if (!("cruxCls" in $$source)) {
            this["cruxCls"] = 0;
        }
        if (!("cruxFcpMs" in $$source)) {
            this["cruxFcpMs"] = 0;
        }
        if (!("cruxTtfbMs" in $$source)) {
            this["cruxTtfbMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PSIResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PSIResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PSIResult($$parsedSource as Partial<PSIResult>);
    }
}

/**
 * Page is everything known about one crawled URL. It is stored as a JSON blob;
 * the columns SQL needs to filter or sort on are promoted alongside it (see
 * schemaStmts) and derived from this struct by pageRow.
 */
export class Page {
    "url": string;
    "depth": number;
    "source": string;
    "internal": boolean;

    /**
     * transport
     */
    "status": number;
    "contentType": string;
    "kind": string;
    "sizeBytes": number;
    "responseMs": number;
    "errorType"?: string;
    "error"?: string;
    "redirects": Hop[];
    "redirectTo"?: string;
    "lastMod"?: string;

    /**
     * head
     */
    "title": string;

    /**
     * every <title>, to flag multiples
     */
    "titles": string[];
    "metaDesc": string;
    "metaDescs": string[];
    "h1": string[];
    "h2": string[];
    "h3": string[];
    "wordCount": number;
    "textRatio": number;
    "lang": string;
    "charset": string;
    "viewport": string;
    "canonical": string;
    "canonicals": string[];
    "metaRobots": string;
    "xRobotsTag": string;
    "metaRefresh"?: string;
    "relNext"?: string;
    "relPrev"?: string;
    "author"?: string;
    "keywords"?: string;
    "generator"?: string;
    "themeColor"?: string;
    "metaTags": { [_ in string]?: string };
    "ogTags": { [_ in string]?: string };
    "twitterTags": { [_ in string]?: string };

    /**
     * raw script bodies, parsed on demand
     */
    "jsonLd": string[];
    "schemaOrg": Schema[];
    "hreflang": Hreflang[];
    "analytics": Analytics;
    "images": Image[];

    /**
     * graph, filled during the crawl and corrected in finalize
     */
    "outlinksInternal": number;
    "outlinksExternal": number;
    "inlinks": number;
    "inlinksUnique": number;

    /**
     * verdicts
     */
    "indexable": boolean;
    "indexability"?: string;
    "robotsState": string;
    "rendered": boolean;

    /**
     * issue codes, for the detail pane
     */
    "issues": string[];
    "crawledAt": string;

    /** Creates a new Page instance. */
    constructor($$source: Partial<Page> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("depth" in $$source)) {
            this["depth"] = 0;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("internal" in $$source)) {
            this["internal"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("contentType" in $$source)) {
            this["contentType"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("responseMs" in $$source)) {
            this["responseMs"] = 0;
        }
        if (!("redirects" in $$source)) {
            this["redirects"] = [];
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("titles" in $$source)) {
            this["titles"] = [];
        }
        if (!("metaDesc" in $$source)) {
            this["metaDesc"] = "";
        }
        if (!("metaDescs" in $$source)) {
            this["metaDescs"] = [];
        }
        if (!("h1" in $$source)) {
            this["h1"] = [];
        }
        if (!("h2" in $$source)) {
            this["h2"] = [];
        }
        if (!("h3" in $$source)) {
            this["h3"] = [];
        }
        if (!("wordCount" in $$source)) {
            this["wordCount"] = 0;
        }
        if (!("textRatio" in $$source)) {
            this["textRatio"] = 0;
        }
        if (!("lang" in $$source)) {
            this["lang"] = "";
        }
        if (!("charset" in $$source)) {
            this["charset"] = "";
        }
        if (!("viewport" in $$source)) {
            this["viewport"] = "";
        }
        if (!("canonical" in $$source)) {
            this["canonical"] = "";
        }
        if (!("canonicals" in $$source)) {
            this["canonicals"] = [];
        }
        if (!("metaRobots" in $$source)) {
            this["metaRobots"] = "";
        }
        if (!("xRobotsTag" in $$source)) {
            this["xRobotsTag"] = "";
        }
        if (!("metaTags" in $$source)) {
            this["metaTags"] = {};
        }
        if (!("ogTags" in $$source)) {
            this["ogTags"] = {};
        }
        if (!("twitterTags" in $$source)) {
            this["twitterTags"] = {};
        }
        if (!("jsonLd" in $$source)) {
            this["jsonLd"] = [];
        }
        if (!("schemaOrg" in $$source)) {
            this["schemaOrg"] = [];
        }
        if (!("hreflang" in $$source)) {
            this["hreflang"] = [];
        }
        if (!("analytics" in $$source)) {
            this["analytics"] = (new Analytics());
        }
        if (!("images" in $$source)) {
            this["images"] = [];
        }
        if (!("outlinksInternal" in $$source)) {
            this["outlinksInternal"] = 0;
        }
        if (!("outlinksExternal" in $$source)) {
            this["outlinksExternal"] = 0;
        }
        if (!("inlinks" in $$source)) {
            this["inlinks"] = 0;
        }
        if (!("inlinksUnique" in $$source)) {
            this["inlinksUnique"] = 0;
        }
        if (!("indexable" in $$source)) {
            this["indexable"] = false;
        }
        if (!("robotsState" in $$source)) {
            this["robotsState"] = "";
        }
        if (!("rendered" in $$source)) {
            this["rendered"] = false;
        }
        if (!("issues" in $$source)) {
            this["issues"] = [];
        }
        if (!("crawledAt" in $$source)) {
            this["crawledAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Page instance from a string or object.
     */
    static createFrom($$source: any = {}): Page {
        const $$createField11_0 = $$createType7;
        const $$createField15_0 = $$createType5;
        const $$createField17_0 = $$createType5;
        const $$createField18_0 = $$createType5;
        const $$createField19_0 = $$createType5;
        const $$createField20_0 = $$createType5;
        const $$createField27_0 = $$createType5;
        const $$createField37_0 = $$createType4;
        const $$createField38_0 = $$createType4;
        const $$createField39_0 = $$createType4;
        const $$createField40_0 = $$createType5;
        const $$createField41_0 = $$createType9;
        const $$createField42_0 = $$createType11;
        const $$createField43_0 = $$createType12;
        const $$createField44_0 = $$createType14;
        const $$createField53_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("redirects" in $$parsedSource) {
            $$parsedSource["redirects"] = $$createField11_0($$parsedSource["redirects"]);
        }
        if ("titles" in $$parsedSource) {
            $$parsedSource["titles"] = $$createField15_0($$parsedSource["titles"]);
        }
        if ("metaDescs" in $$parsedSource) {
            $$parsedSource["metaDescs"] = $$createField17_0($$parsedSource["metaDescs"]);
        }
        if ("h1" in $$parsedSource) {
            $$parsedSource["h1"] = $$createField18_0($$parsedSource["h1"]);
        }
        if ("h2" in $$parsedSource) {
            $$parsedSource["h2"] = $$createField19_0($$parsedSource["h2"]);
        }
        if ("h3" in $$parsedSource) {
            $$parsedSource["h3"] = $$createField20_0($$parsedSource["h3"]);
        }
        if ("canonicals" in $$parsedSource) {
            $$parsedSource["canonicals"] = $$createField27_0($$parsedSource["canonicals"]);
        }
        if ("metaTags" in $$parsedSource) {
            $$parsedSource["metaTags"] = $$createField37_0($$parsedSource["metaTags"]);
        }
        if ("ogTags" in $$parsedSource) {
            $$parsedSource["ogTags"] = $$createField38_0($$parsedSource["ogTags"]);
        }
        if ("twitterTags" in $$parsedSource) {
            $$parsedSource["twitterTags"] = $$createField39_0($$parsedSource["twitterTags"]);
        }
        if ("jsonLd" in $$parsedSource) {
            $$parsedSource["jsonLd"] = $$createField40_0($$parsedSource["jsonLd"]);
        }
        if ("schemaOrg" in $$parsedSource) {
            $$parsedSource["schemaOrg"] = $$createField41_0($$parsedSource["schemaOrg"]);
        }
        if ("hreflang" in $$parsedSource) {
            $$parsedSource["hreflang"] = $$createField42_0($$parsedSource["hreflang"]);
        }
        if ("analytics" in $$parsedSource) {
            $$parsedSource["analytics"] = $$createField43_0($$parsedSource["analytics"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField44_0($$parsedSource["images"]);
        }
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField53_0($$parsedSource["issues"]);
        }
        return new Page($$parsedSource as Partial<Page>);
    }
}

/**
 * Row is the grid's projection of a page: exactly the columns the current tab
 * asked for, positionally aligned to RowQuery.Cols.
 * 
 * A map would be the obvious shape, but Wails renders Go maps as
 * `{[_ in string]?: T}` — every value optional and needing narrowing — and at
 * 25 columns × 50k rows the keys roughly double the payload.
 */
export class Row {
    /**
     * the URL; stable across sorts and live inserts
     */
    "id": string;
    "cells": string[];
    "status": number;
    "flags": number;

    /** Creates a new Row instance. */
    constructor($$source: Partial<Row> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("cells" in $$source)) {
            this["cells"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("flags" in $$source)) {
            this["flags"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Row instance from a string or object.
     */
    static createFrom($$source: any = {}): Row {
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cells" in $$parsedSource) {
            $$parsedSource["cells"] = $$createField1_0($$parsedSource["cells"]);
        }
        return new Row($$parsedSource as Partial<Row>);
    }
}

/**
 * RowPage is one window of grid rows.
 */
export class RowPage {
    "rows": Row[];
    "offset": number;

    /**
     * -1 when not requested
     */
    "total": number;

    /**
     * matches ProgressEvent.Revision
     */
    "revision": number;

    /** Creates a new RowPage instance. */
    constructor($$source: Partial<RowPage> = {}) {
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("revision" in $$source)) {
            this["revision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowPage instance from a string or object.
     */
    static createFrom($$source: any = {}): RowPage {
        const $$createField0_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField0_0($$parsedSource["rows"]);
        }
        return new RowPage($$parsedSource as Partial<RowPage>);
    }
}

/**
 * RowQuery is one grid window request.
 */
export class RowQuery {
    "runId": string;
    "tab": string;
    "filter": string;
    "search": string;
    "cols": string[];
    "sort": string;
    "desc": boolean;
    "offset": number;
    "limit": number;

    /**
     * IDs pins the window to an explicit URL set — how "export selected"
     * works: the grid's multi-select rides the same query as everything else.
     */
    "ids": string[];

    /**
     * WantTotal asks for COUNT(*). The grid only needs it when the filter
     * changed, and skipping it turns every scroll into an index-only read.
     */
    "wantTotal": boolean;

    /** Creates a new RowQuery instance. */
    constructor($$source: Partial<RowQuery> = {}) {
        if (!("runId" in $$source)) {
            this["runId"] = "";
        }
        if (!("tab" in $$source)) {
            this["tab"] = "";
        }
        if (!("filter" in $$source)) {
            this["filter"] = "";
        }
        if (!("search" in $$source)) {
            this["search"] = "";
        }
        if (!("cols" in $$source)) {
            this["cols"] = [];
        }
        if (!("sort" in $$source)) {
            this["sort"] = "";
        }
        if (!("desc" in $$source)) {
            this["desc"] = false;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("ids" in $$source)) {
            this["ids"] = [];
        }
        if (!("wantTotal" in $$source)) {
            this["wantTotal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): RowQuery {
        const $$createField4_0 = $$createType5;
        const $$createField9_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cols" in $$parsedSource) {
            $$parsedSource["cols"] = $$createField4_0($$parsedSource["cols"]);
        }
        if ("ids" in $$parsedSource) {
            $$parsedSource["ids"] = $$createField9_0($$parsedSource["ids"]);
        }
        return new RowQuery($$parsedSource as Partial<RowQuery>);
    }
}

/**
 * RunStatus is the poll fallback for a frontend that missed an event.
 */
export class RunStatus {
    "runId": string;
    "jobId"?: string;
    "state": string;
    "phase": string;
    "found": number;
    "crawled": number;
    "revision": number;

    /** Creates a new RunStatus instance. */
    constructor($$source: Partial<RunStatus> = {}) {
        if (!("runId" in $$source)) {
            this["runId"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("found" in $$source)) {
            this["found"] = 0;
        }
        if (!("crawled" in $$source)) {
            this["crawled"] = 0;
        }
        if (!("revision" in $$source)) {
            this["revision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): RunStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunStatus($$parsedSource as Partial<RunStatus>);
    }
}

/**
 * RunSummary is one row of the history list.
 */
export class RunSummary {
    "id": string;
    "seedUrl": string;
    "host": string;
    "mode": string;
    "state": string;
    "phase": string;
    "stopReason"?: string;
    "resumable": boolean;
    "found": number;
    "crawled": number;
    "issues": number;
    "startedAt": string;
    "finishedAt"?: string;
    "durationMs": number;
    "options": Options;

    /**
     * SizeBytes is this run's share of the workspace database. Storing the full
     * link graph is what makes the Links tab possible and it is not cheap, so
     * the cost is shown rather than hidden.
     */
    "sizeBytes": number;

    /** Creates a new RunSummary instance. */
    constructor($$source: Partial<RunSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("seedUrl" in $$source)) {
            this["seedUrl"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("resumable" in $$source)) {
            this["resumable"] = false;
        }
        if (!("found" in $$source)) {
            this["found"] = 0;
        }
        if (!("crawled" in $$source)) {
            this["crawled"] = 0;
        }
        if (!("issues" in $$source)) {
            this["issues"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("options" in $$source)) {
            this["options"] = (new Options());
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): RunSummary {
        const $$createField14_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField14_0($$parsedSource["options"]);
        }
        return new RunSummary($$parsedSource as Partial<RunSummary>);
    }
}

/**
 * Schema is one microdata itemscope.
 */
export class Schema {
    "type": string;
    "properties": { [_ in string]?: string };

    /** Creates a new Schema instance. */
    constructor($$source: Partial<Schema> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("properties" in $$source)) {
            this["properties"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Schema instance from a string or object.
     */
    static createFrom($$source: any = {}): Schema {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField1_0($$parsedSource["properties"]);
        }
        return new Schema($$parsedSource as Partial<Schema>);
    }
}

/**
 * StartedCrawl is what Start/Resume hand back.
 * 
 * JobID and RunID are the same string for a fresh crawl and differ for a resume,
 * exactly as in indexcheck: the job id addresses the goroutine (progress,
 * cancel) while the run id addresses the rows in SQLite.
 */
export class StartedCrawl {
    "jobId": string;
    "runId": string;

    /** Creates a new StartedCrawl instance. */
    constructor($$source: Partial<StartedCrawl> = {}) {
        if (!("jobId" in $$source)) {
            this["jobId"] = "";
        }
        if (!("runId" in $$source)) {
            this["runId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartedCrawl instance from a string or object.
     */
    static createFrom($$source: any = {}): StartedCrawl {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartedCrawl($$parsedSource as Partial<StartedCrawl>);
    }
}

// Private type creation functions
const $$createType0 = GraphNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = GraphEdge.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = Hop.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Schema.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = Hreflang.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = Analytics.createFrom;
const $$createType13 = Image.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = Row.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = Options.createFrom;
