// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel is the jobId-addressed form the shared progress UI uses.
 */
export function Cancel(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(1086680056, jobID);
}

/**
 * ClearHistory removes every stored crawl.
 */
export function ClearHistory(): $CancellablePromise<string> {
    return $Call.ByID(32260685);
}

/**
 * DefaultOptions gives the frontend the same numbers Go clamps to, so the two
 * never disagree about what "default" means.
 */
export function DefaultOptions(): $CancellablePromise<$models.Options> {
    return $Call.ByID(4043503907).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteRun removes a run's rows in chunks, returning the job id doing it.
 * 
 * A single DELETE over a 5M-row link table holds the workspace's only writable
 * connection for seconds, freezing every other tool's grid — so the work is
 * chunked and backgrounded, and the run row is hidden immediately.
 */
export function DeleteRun(runID: string): $CancellablePromise<string> {
    return $Call.ByID(3721318010, runID);
}

/**
 * Export writes the current view to a file the user picks.
 * 
 * The query is the grid's own, so what lands in the file is exactly what is on
 * screen — same tab, filter, search and sort.
 */
export function Export(format: string, q: $models.RowQuery): $CancellablePromise<string> {
    return $Call.ByID(3478327880, format, q);
}

/**
 * Facets returns every tab and filter count in one call, so the Overview tree
 * never has to poll.
 */
export function Facets(runID: string): $CancellablePromise<{ [_ in string]?: number }> {
    return $Call.ByID(2481876274, runID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Graph returns the top-N pages by inlinks plus every edge between them.
 * 
 * Edges are scanned narrow and filtered in Go: an IN-list of 3000 ids twice
 * over would blow SQLite's bind limit, while one pass over even 5M two-int
 * rows is cheap and closes the cursor before anything else runs.
 */
export function Graph(runID: string, maxNodes: number): $CancellablePromise<$models.GraphData> {
    return $Call.ByID(289564578, runID, maxNodes).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Inlinks lists the pages linking to a URL.
 */
export function Inlinks(runID: string, rawURL: string, offset: number, limit: number): $CancellablePromise<$models.LinkRow[]> {
    return $Call.ByID(1605635774, runID, rawURL, offset, limit).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * IssueCatalog is bound to the frontend so the Issues tab and the Overview tree
 * can label and colour every rule without duplicating this table in TypeScript.
 */
export function IssueCatalog(): $CancellablePromise<$models.IssueInfo[]> {
    return $Call.ByID(3782899252).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * OnLaunch is the tools.Starter hook: the shell calls it on every built tool
 * that has one, so main never names this tool.
 */
export function OnLaunch(): $CancellablePromise<void> {
    return $Call.ByID(1187142604);
}

/**
 * Opportunities lists every audit in the run, heaviest first.
 */
export function Opportunities(runID: string): $CancellablePromise<$models.Opportunity[]> {
    return $Call.ByID(3201327443, runID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * OpportunityPages lists the URLs one audit fires on, worst first.
 */
export function OpportunityPages(runID: string, auditID: string): $CancellablePromise<$models.OpportunityPage[]> {
    return $Call.ByID(145177217, runID, auditID).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * Outlinks lists what a page links to.
 */
export function Outlinks(runID: string, rawURL: string, offset: number, limit: number): $CancellablePromise<$models.LinkRow[]> {
    return $Call.ByID(2379053119, runID, rawURL, offset, limit).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Page returns the full stored record for one URL — the only read that touches
 * the JSON blob, and only ever one row of it.
 */
export function Page(runID: string, rawURL: string): $CancellablePromise<$models.Page> {
    return $Call.ByID(1191878161, runID, rawURL).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * PageSpeed measures the given URLs as a background job and returns its id.
 */
export function PageSpeed(runID: string, urls: string[], strategy: string): $CancellablePromise<string> {
    return $Call.ByID(2268122316, runID, urls, strategy);
}

/**
 * PageSpeedResults lists every stored measurement for a run, newest first.
 */
export function PageSpeedResults(runID: string): $CancellablePromise<$models.PSIResult[]> {
    return $Call.ByID(1329295890, runID).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * Pause stops dispatching without ending the run. The job goroutine stays alive
 * holding the frontier, so Resume continues exactly where it left off.
 */
export function Pause(runID: string): $CancellablePromise<void> {
    return $Call.ByID(2697399868, runID);
}

/**
 * PendingPageSpeedCount is what the PageSpeed tab's Run button counts: how many
 * pages of this run still have no measurement for this device.
 */
export function PendingPageSpeedCount(runID: string, strategy: string): $CancellablePromise<number> {
    return $Call.ByID(2425969336, runID, strategy);
}

/**
 * RecoverRuns is called once at startup so a crawl interrupted by closing the
 * app shows as resumable rather than running.
 */
export function RecoverRuns(): $CancellablePromise<void> {
    return $Call.ByID(349129804);
}

/**
 * Recrawl starts a fresh run with the same seed and options.
 */
export function Recrawl(runID: string): $CancellablePromise<$models.StartedCrawl> {
    return $Call.ByID(1758559930, runID).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * Resume continues a paused crawl.
 * 
 * Two paths: a live gate is simply lifted, while a run paused by closing the
 * app is restarted from its checkpoint — in which case the job id differs from
 * the run id, exactly as in indexcheck's rerun.
 */
export function Resume(runID: string): $CancellablePromise<$models.StartedCrawl> {
    return $Call.ByID(3697905157, runID).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * Rows returns one window of grid rows.
 */
export function Rows(q: $models.RowQuery): $CancellablePromise<$models.RowPage> {
    return $Call.ByID(1319346783, q).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * Runs returns the crawl history, newest first, with each run's approximate
 * share of the workspace database.
 */
export function Runs(): $CancellablePromise<$models.RunSummary[]> {
    return $Call.ByID(2981977416).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * Start begins a crawl.
 * 
 * seeds is one URL in spider mode, or the whole list in list mode.
 */
export function Start(seeds: string[], opts: $models.Options): $CancellablePromise<$models.StartedCrawl> {
    return $Call.ByID(369107634, seeds, opts).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * Status is the poll fallback for a frontend that missed an event.
 * 
 * Read-only on purpose, and this is the call where it matters most: the screen
 * polls it every second or two for the whole length of a crawl, which is
 * exactly when the crawl is holding the single writer connection. Every counter
 * it reports is written by a committed statement, so the read-only handle sees
 * the same numbers.
 */
export function Status(runID: string): $CancellablePromise<$models.RunStatus> {
    return $Call.ByID(3984659732, runID).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * Stop ends a crawl, keeping everything it found.
 */
export function Stop(runID: string): $CancellablePromise<void> {
    return $Call.ByID(1537914098, runID);
}

/**
 * StopPageSpeed ends the measurements without touching the crawl.
 * 
 * Stopping the pump is enough on both paths: the crawl's drain sees it retire,
 * and the standalone job's Wait returns. Everything measured so far is kept,
 * and the pending query means a later Run picks up exactly where this left off.
 */
export function StopPageSpeed(runID: string): $CancellablePromise<void> {
    return $Call.ByID(3170681956, runID);
}

// Private type creation functions
const $$createType0 = $models.Options.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $models.GraphData.createFrom;
const $$createType3 = $models.LinkRow.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.IssueInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.Opportunity.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.OpportunityPage.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.Page.createFrom;
const $$createType12 = $models.PSIResult.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.StartedCrawl.createFrom;
const $$createType15 = $models.RowPage.createFrom;
const $$createType16 = $models.RunSummary.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $models.RunStatus.createFrom;
